management:
  context-path: /zenikadmin
  security:
    enabled: true

security:
  basic:
    path: /zenikadmin/**


lunchplace:
  mongo:
    host: localhost
    port: 27001
    user: lunchplace
    password: rulez
    db: lunchplace-dev